language: php

php:
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --testsuite "Unit" --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)