name: "Check plugin code"

on:
  push:
    branches: [ master, v3, v4 ]
  pull_request:
    branches: [ master, v3, v4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.30'
        tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Check PHP Version
      run: php --version

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      run: vendor/bin/phpcs --no-cache --standard=.phpcs.xml.dist simple-jwt-login/ tests/ --extensions=php

    - name: Run PHPMD
      run: vendor/bin/phpmd simple-jwt-login/ text phpmd.xml

    - name: Run phpstan on plugin
      run: vendor/bin/phpstan analyse simple-jwt-login -c phpstan.neon --memory-limit=256M
